services:
  app:
    build: .
    container_name: coffee_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: coffee_mysql
    restart: always
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: